- string_id: "difda"
  name: "Difda"
  dms: "2° 50' Aries"
- string_id: "pleiades"
  name: "Pleiades"
  dms: "30° 13' Taurus"
- string_id: "hyades"
  name: "Hyades"
  dms: "6° 0' Gemini"
- string_id: "aldebaran"
  name: "Aldebaran"
  dms: "10° 2' Gemini"
- string_id: "rigel"
  name: "Rigel"
  dms: "17° 5' Gemini"
- string_id: "antares"
  name: "Antares"
  dms: "10° 1' Scorpio"
- string_id: "rastaban"
  name: "Rastaban"
  dms: "12° 13' Scorpio"
- string_id: "vega"
  name: "Vega"
  dms: "15° 34' Gemini"
- string_id: "altair"
  name: "Altair"
  dms: "2° 2' Aquarius"
- string_id: "fomalhaut"
  name: "Fomalhaut"
  dms: "4° 7' Pisces"
- string_id: "deneb_adige"
  name: "Deneb Adige"
  dms: "5° 31' Pisces"
- string_id: "bellatrix"
  name: "Bellatrix"
  dms: "21° 43' Gemini"
- string_id: "capella"
  name: "Capella"
  dms: "22° 6' Gemini"
- string_id: "el_nath"
  name: "El Nath"
  dms: "22° 41' Gemini"
- string_id: "polaris"
  name: "Polaris"
  dms: "28° 49' Gemini"
- string_id: "the_pole_star"
  name: "The Pole Star"
  dms: "28° 49' Gemini"
- string_id: "betelgeuse"
  name: "Betelgeuse"
  dms: "29° 0' Gemini"
- string_id: "pisces"
  name: "Pisces"
  dms: "23° 44' Pisces"
- string_id: "canopus"
  name: "Canopus"
  dms: "15° 6' Cancer"
- string_id: "castor"
  name: "Castor"
  dms: "20° 29' Cancer"
- string_id: "pollux"
  name: "Pollux"
  dms: "23° 28' Cancer"
- string_id: "procyon"
  name: "Procyon"
  dms: "26° 2' Cancer"
- string_id: "serpentis"
  name: "Serpentis"
  dms: "19° 15' Scorpio"
- string_id: "algenubi"
  name: "Algenubi"
  dms: "20° 57' Leo"
- string_id: "regulus"
  name: "Regulus"
  dms: "30° 8' Leo"
- string_id: "mizar"
  name: "Mizar"
  dms: "15° 57' Virgo"
- string_id: "denebola"
  name: "Denebola"
  dms: "21° 53' Virgo"
- string_id: "markeb"
  name: "Markeb"
  dms: "23° 44' Virgo"
- string_id: "algorab"
  name: "Algorab"
  dms: "13° 42' Libra"
- string_id: "spica"
  name: "Spica"
  dms: "24° 5' Libra"
- string_id: "dheneb"
  name: "Dheneb"
  dms: "20° 3' Capricorn"
- string_id: "hamal"
  name: "Hamal"
  dms: "0° 15' Aries"
- string_id: "algedi"
  name: "Algedi"
  dms: "4° 1' Capricorn"
- string_id: "arcturus"
  name: "Arcturus"
  dms: "24° 29' Virgo"
- string_id: "ras_alhague"
  name: "Ras Alhague"
  dms: "22° 42' Scorpio"
- string_id: "mulam_the_root"
  name: "Mulam: the Root"
  dms: "26° 15' Sagittarius"
- string_id: "polis"
  name: "Polis"
  dms: "0° 15' Aries"
- string_id: "mirach"
  name: "Mirach"
  dms: "0° 39' Pisces"
- string_id: "deneb_kaitos"
  name: "Deneb Kaitos"
  dms: "2° 50' Pisces"
- string_id: "agena"
  name: "Agena"
  dms: "4° 43' Libra"
- string_id: "spiculum"
  name: "Spiculum"
  dms: "1° 19' Capricorn"
- string_id: "talitha"
  name: "Talitha"
  dms: "3° 3' Leo"
- string_id: "almach"
  name: "Almach"
  dms: "14° 30' Aries"
- string_id: "rana"
  name: "Rana"
  dms: "21° 7' Taurus"
- string_id: "caput_algol"
  name: "Caput Algol"
  dms: "26° 25' Taurus"
- string_id: "alphard"
  name: "Alphard"
  dms: "27° 23' Leo"
- string_id: "al_jabhah"
  name: "Al Jabhah"
  dms: "27° 56' Leo"
- string_id: "benetnash"
  name: "Benetnash (Alkaid)"
  dms: "27° 12' Virgo"
- string_id: "caput_hercules"
  name: "Caput Hercules"
  dms: "10° 39' Leo"
- string_id: "alpheratz"
  name: "Alpheratz"
  dms: "2° 18' Aquarius"
- string_id: "algenib"
  name: "Algenib"
  dms: "9° 24' Aries"
- string_id: "phact"
  name: "Phact"
  dms: "22° 31' Gemini"
- string_id: "alphecca"
  name: "Alphecca"
  dms: "12° 34' Scorpio"
- string_id: "acubens"
  name: "Acubens"
  dms: "13° 50' Leo"
- string_id: "merak"
  name: "Merak"
  dms: "19° 21' Leo"
- string_id: "ras_elased_aust"
  name: "Ras Elased Aust"
  dms: "20° 57' Leo"
- string_id: "thuban"
  name: "Thuban"
  dms: "7° 42' Virgo"
- string_id: "terebellum"
  name: "Terebellum"
  dms: "26° 6' Capricorn"
- string_id: "albali"
  name: "Albali"
  dms: "11° 58' Aquarius"
- string_id: "nashira"
  name: "Nashira"
  dms: "22° 27' Aquarius"
- string_id: "gienah"
  name: "Gienah"
  dms: "28° 0' Aquarius"
- string_id: "sadalsuud"
  name: "Sadalsuud"
  dms: "23° 44' Aquarius"
- string_id: "alnasl"
  name: "Alnasl"
  dms: "1° 31' Capricorn"
- string_id: "zuben_algenubi"
  name: "Zuben Algenubi"
  dms: "15° 19' Scorpio"
- string_id: "kornephoros"
  name: "Kornephoros"
  dms: "7° 15' Capricorn"
- string_id: "achernar"
  name: "Achernar"
  dms: "25° 22' Pisces"
